### ISSUE TITLE
Filters - Matching Categories removes autodl of non-matched catagories

### ISSUE THREAD

**Issue by milltertime** [autodl-community/autodl-rutorrent#25]
Under the advanced tab I added a specific category to always download.
Once the filter on the category blocks ether other download that was working before that did not match the category added.  

Any suggestions or ideas on how this can be worked around?

Also under the TV/Movies section if you attempt to filter to for example Movies from 2015-2016.  Most TV shows do no include the year released thus you are missing current year shows since they have no year in the name.

**Comment by thebigmunch** [comment]
I have no idea what you're talking about with the first part. It doesn't make any sense. It's also unrelated to the ruTorrent plugin and sounds more like a support issue you should take to the IRC channel rather than the Issue Tracker.

As for the 2nd, I'll save you from asking that in there. Of course you can't filter by information that isn't provided.
