### ISSUE TITLE
Is there a way to bypass a bad certificate (SSL) on the IRC Server?

### ISSUE THREAD

**Issue by PFCKrutonium** [autodl-community/autodl-rutorrent#31]
Because I can't get it to connect to a IRC Server with a self signed SSL Certificate.

**Comment by thebigmunch** [comment]
This should be posted on the autodl-irssi issue tracker, if anything; this is the issue tracker for the ruTorrent plugin. But then, autodl-irssi is just a plugin for irssi, which handles all the IRC connections. You didn't post any kind of error or anything to help with your issue, but I'd guess it's not anything to do with autodl-irssi since it just sends commands to irssi.

**Comment by PFCKrutonium** [comment]
I can't even find the _logs_. and could you link me to the correct place?
