### ISSUE TITLE
Return value from attemptZeroConfig() is not checked

### ISSUE THREAD

**Issue by weaselBuddha** [autodl-community/autodl-rutorrent#37]
What the user sees:  _Error downloading files. Make sure autodl-irssi is started and configured properly (eg. password, port number): Error getting files listing: Error: Invalid port ()! Initialize port in conf.php_

If ~/.autodl/autodl.cfg exists and is local, the port and password from conf.php is not used. But if autodl.cfg is empty the zero configuration process fails to recognize it did not get a port or password. 

In getConf.php, after calling attemptZeroConfig( ), $config is not checked as null, giving both a null port and null password.

We use autodl2.cfg for just the port and and password settings. This allows the tracker and filter configurations to be portable. An empty autodl.cfg is created by running irssi/autodl the first time.

**Comment by thebigmunch** [comment]
Sorry, I kept forgetting to respond to this.

I forgot that the gui-server options could be set in ``autodl2.cfg`` when @anthonyryan1 submitted that PR. Frankly, I've never found a good reason for it to exist and specify those options in ``autodl.cfg``. It doesn't really help with portability, since you'll have to set them in one file or another anyway. However, it should still be checked by parsing the file and conditionally merging the two config files with ``autodl2.cfg`` over ``autodl.cfg`` to match autodl-irssi behavior.

As for the error when these options aren't set, I will likely just update it to inform user to set the gui-server options in ``autodl.cfg`` rather than ``conf.php``. That is what would be required either way. And once the above problem is fixed, ``conf.php`` never comes into play.

**Comment by anthonyryan1** [comment]
I'll have a pull request ready for testing first thing in the morning. My apologies for the regression.

**Comment by anthonyryan1** [comment]
Could I ask you to please test the version of getConf here, and let me know if it properly resolves the issue for you:

https://github.com/anthonyryan1/autodl-rutorrent/blob/90cbd887e87a344ecce940fe423adfa4016a9728/getConf.php
